## Manipulating Matrices

#### Creating Arrays and Matrices

In [1]:
import numpy as np

row = np.array([1,2,3])
columns = np.array([[1],[2],[3]])

matrix = np.mat([[1,2], [3,4], [5,6]])

#### Create Sparse Matrix: Stores only nonzero elements

In [2]:
from scipy import sparse

matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

matrix_sparse = sparse.csr_matrix(matrix_large)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


#### Selecting Elements

In [3]:
matrix[2:] # select everything after element
matrix[:2] # select all rows including n-th
matrix[1] # select row
matrix[-1] # select last element 
matrix[:2, 1:] # select submatrix

matrix([[2],
        [4]])

#### Describing Matrices

In [4]:
# create matrix
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# create function
add_100 = lambda i:i +100

# create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# call function
vectorized_add_100(matrix)

# is equivalent to
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

#### Find max and min in array

In [5]:
np.max(matrix) # find max element
np.min(matrix) # find min element
np.max(matrix, axis = 0) # find max element of each col
np.max(matrix, axis = 1) # find max element of each row 

array([3, 6, 9])

#### Calculate mean, standart deviation, variance 

In [6]:
np.mean(matrix, axis = 0) # calculate mean of each col
np.std(matrix, axis = 1) # calculate standart deviation of each rows
np.var(matrix, axis = 0) # calculate variance of each col

array([6., 6., 6.])

#### Reshaping Arrays using matrix.size

In [7]:
matrix.reshape(1,9) # change matrix shape to 1 row, 9 col
matrix.reshape(1,-1) # change matrice to one row (as many col needed)
matrix.reshape(9) # create 1-D array
matrix.flatten() # create 1-D array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Transpose matrix

In [8]:
matrix.transpose() # transpose matrix 
matrix.T # transpose matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Linear Algebra

In [9]:
np.linalg.matrix_rank(matrix) # Find Matrix Rank: max of linear independant rows

np.linalg.det(matrix) # Calculate Determinant of a matrix 

matrix.diagonal() # find matrix diagonal
matrix.diagonal(offset = 1) # find matrix diagonal with one above

matrix.trace() # return trace: sum of diagonal element
sum(matrix.diagonal()) # return trace: sum of diagonal element

eigenvalues, eigenvectors = np.linalg.eig(matrix) # Find eighten values and eighten vectors

np.dot(matrix, matrix) # multiplication matricielle
np.add(matrix, matrix) # addition matricielle
np.subtract(matrix, matrix) # soustraction matricielle
matrix + matrix # addition matricielle
matrix @ matrix # multiplication matricielle
matrix * matrix # element-wise multiplication

mat_squared = np.array([
    [1,2],
    [3,4]
])

np.linalg.inv(mat_squared) # return inverse of matrix
mat_squared @ np.linalg.inv(mat_squared)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])